---
name: "Valida Roles Ansible"

on:
  workflow_call:
    inputs:
      python_version:
        description: "Versão do python"
        required: false
        type: string
        default: '3.9'
      os_version:
        description: "Versão do sistema operacional"
        required: false
        default: "ubuntu-20.04"
        type: string    
    secrets:
      token:
        required: true
jobs:
  linter:
    runs-on: ${{ inputs.os_version }} 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Run Linters
        run: |
          ansible-lint

  molecule:
    runs-on: ${{ inputs.os_version }}
    strategy:
      matrix:
        molecule_distro: [ubuntu1804, ubuntu2004]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Force GitHub Actions' docker daemon to use vfs.
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
      - name: Test with molecule
        run: |
          molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          # Mudar a cor de mensagens de debug para aparecer melhor no fundo
          # escuro dos logs do GitHub Action.
          ANSIBLE_COLOR_DEBUG: "bright gray"
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
